from integrations.firewall import parse_iptables_save, parse_ufw_status, port_reachable

# 실제 `ufw status verbose` 출력 (v6 중복 행 포함)
UFW_ACTIVE = """Status: active
Logging: on (low)
Default: deny (incoming), allow (outgoing), disabled (routed)
New profiles: skip

To                         Action      From
--                         ------      ----
22/tcp                     ALLOW IN    Anywhere
80/tcp                     ALLOW IN    Anywhere
22/tcp (v6)                ALLOW IN    Anywhere (v6)
80/tcp (v6)                ALLOW IN    Anywhere (v6)
"""

UFW_INACTIVE = "Status: inactive\n"

UFW_MIXED = """Status: active
Logging: on (low)
Default: deny (incoming), allow (outgoing), disabled (routed)
New profiles: skip

To                         Action      From
--                         ------      ----
6000:6007/tcp              ALLOW IN    Anywhere
OpenSSH                    ALLOW IN    Anywhere
Samba                      ALLOW IN    192.168.0.0/16
3306/tcp                   DENY IN     Anywhere
53                         ALLOW IN    Anywhere
6000:6007/tcp (v6)         ALLOW IN    Anywhere (v6)
"""

IPTABLES_SAVE = """# Generated by iptables-save v1.8.10
*filter
:INPUT DROP [0:0]
:FORWARD DROP [0:0]
:OUTPUT ACCEPT [120:9000]
-A INPUT -i lo -j ACCEPT
-A INPUT -p tcp -m tcp --dport 22 -j ACCEPT
-A INPUT -p udp -m udp --dport 123 -j ACCEPT
-A INPUT -p tcp -m tcp --dport 3306 -j DROP
COMMIT
"""


def _snapshot(parsed, backend="ufw", available=True):
    """FirewallClient.snapshot() 과 같은 모양을 파싱 결과로 만든다 (subprocess 없이 테스트하기 위함)."""
    from integrations.firewall import _allowed_ports
    rules = parsed.get("rules", [])
    return {
        "available": available, "backend": backend, "active": parsed.get("active", True),
        "default_incoming": parsed.get("default_incoming", ""), "rules": rules,
        "allowed": _allowed_ports(rules), "reason": "", "fix_hint": "",
    }


def test_ufw_active_allowed_ports_deduplicated():
    p = parse_ufw_status(UFW_ACTIVE)
    assert p["active"] is True and p["default_incoming"] == "deny"
    # v6 중복 행이 있어도 허용 포트는 중복 없이 오름차순
    assert _snapshot(p)["allowed"] == [{"port": 22, "proto": "tcp"}, {"port": 80, "proto": "tcp"}]
    assert all(r["action"] == "ALLOW" for r in p["rules"])
    assert [r["v6"] for r in p["rules"]] == [False, False, True, True]
    assert p["rules"][0]["from"] == "Anywhere" and p["rules"][0]["raw"].startswith("22/tcp")


def test_ufw_inactive():
    p = parse_ufw_status(UFW_INACTIVE)
    assert p["active"] is False and p["rules"] == [] and p["default_incoming"] == ""
    # 방화벽이 꺼져 있으면 필터링이 없다 → 도달 가능
    assert port_reachable(_snapshot(p), 22) is True


def test_ufw_port_range_and_named_service():
    p = parse_ufw_status(UFW_MIXED)
    ports = {(r["port"], r["proto"]) for r in p["rules"]}
    assert (6000, "tcp") in ports and (6007, "tcp") in ports   # 범위 전개
    assert (22, "tcp") in ports                                 # OpenSSH → 22/tcp
    assert (None, "any") in ports                               # 숫자로 환원 못 하는 Samba
    assert (53, "any") in ports                                 # 프로토콜 없는 포트
    named = [r for r in p["rules"] if r["port"] is None]
    assert named and named[0]["raw"].startswith("Samba")
    snap = _snapshot(p)
    assert {"port": 3306, "proto": "tcp"} not in snap["allowed"]  # DENY 는 허용 목록에서 빠진다
    assert {"port": 6000, "proto": "tcp"} in snap["allowed"]
    assert {"port": 53, "proto": "udp"} in snap["allowed"]        # proto any 는 tcp/udp 모두
    assert port_reachable(snap, 3306) is False


def test_iptables_save_fallback():
    p = parse_iptables_save(IPTABLES_SAVE)
    assert p["default_incoming"] == "deny"
    snap = _snapshot(p, backend="iptables")
    assert snap["allowed"] == [{"port": 22, "proto": "tcp"}, {"port": 123, "proto": "udp"}]
    assert port_reachable(snap, 22) is True
    assert port_reachable(snap, 3306) is False
    assert port_reachable(snap, 22, "udp") is False


def test_port_reachable_true_false_none():
    snap = _snapshot(parse_ufw_status(UFW_ACTIVE))
    assert port_reachable(snap, 22, "tcp") is True            # 허용 규칙 있음
    assert port_reachable(snap, 8080, "tcp") is False         # 기본 정책 deny + 매칭 규칙 없음
    unavailable = {"available": False, "backend": "", "active": False, "default_incoming": "",
                   "rules": [], "allowed": [], "reason": "ufw 미설치", "fix_hint": "sudo apt install ufw"}
    assert port_reachable(unavailable, 22) is None            # 방화벽 상태를 못 읽음
